export const SITE_CONFIG = {
  name: 'WCC Fashions',
  fullName: 'Western Clothing Co',
  tagline: 'Precision in Every Stitch',
  description:
    'UAE-based B2B manufacturing group for garments, uniforms, hospitality textiles, home furnishings, and fragrance. Bulk supply with quote-based pricing only.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://wccfashions.com',
  phone: process.env.NEXT_PUBLIC_COMPANY_PHONE || '+971565440678',
  email: process.env.NEXT_PUBLIC_COMPANY_EMAIL || 'wccfashions.info@gmail.com',
  whatsapp: process.env.NEXT_PUBLIC_COMPANY_WHATSAPP || '+971565440678',
  address: 'Dubai, United Arab Emirates',
  founded: '2001',
  countries: '50+',
  products: '10,000+',
  years: '25+',
}

export const DIVISIONS = [
  {
    name: 'Garments',
    slug: 'garments',
    icon: 'DIV-01',
    status: 'flagship' as const,
    description: 'Premium garment manufacturing for global export',
    metaTitle: 'Wholesale Garments Manufacturer UAE | Bulk Cotton Shirts, Polos & Formal Wear — WCC Garments',
    metaDescription: 'B2B wholesale garment manufacturer in Dubai, UAE. Premium cotton shirts, polo shirts, formal wear & blazers. Export-grade QC. MOQ from 50 units. Get a bulk quote today.',
    keywords: ['wholesale garments manufacturer UAE', 'bulk t-shirt manufacturer Dubai', 'cotton shirts wholesale UAE', 'garment factory Dubai', 'polo shirt bulk order UAE', 'formal shirts wholesale Dubai', 'B2B garment supplier UAE', 'custom garment manufacturer Middle East', 'blazer manufacturer UAE', 'corporate wear bulk Dubai'],
    heroHeading: 'Premium Garments. Precision-Built for Global Wholesale.',
    heroSubtitle: 'From cotton formal shirts to velvet blazers — crafted for large-scale B2B buyers across 50+ countries.',
    stat1Label: 'MOQ From', stat1Value: '50 Units',
    stat2Label: 'Lead Time', stat2Value: '12–25 Days',
    stat3Label: 'Export QC', stat3Value: 'Grade A',
    categories: [
      { id: 'GAR-CAT-01', name: 'Shirts', slug: 'shirts', status: 'active' as const, displayOrder: 1, subCategories: [] },
      { id: 'GAR-CAT-02', name: 'T-Shirts', slug: 't-shirts', status: 'active' as const, displayOrder: 2, subCategories: [] },
      { id: 'GAR-CAT-03', name: 'Jeans', slug: 'jeans', status: 'active' as const, displayOrder: 3, subCategories: [] },
      { id: 'GAR-CAT-04', name: 'Trousers', slug: 'trousers', status: 'active' as const, displayOrder: 4, subCategories: [] },
      { id: 'GAR-CAT-05', name: 'Cargos', slug: 'cargos', status: 'active' as const, displayOrder: 5, subCategories: [] },
      { id: 'GAR-CAT-06', name: 'Track Pants', slug: 'track-pants', status: 'active' as const, displayOrder: 6, subCategories: [] },
    ],
  },

  {
    name: 'Households',
    slug: 'households',
    icon: 'DIV-02',
    status: 'active' as const,
    description: 'Premium kitchenware, cookware and homecraft essentials',
    metaTitle: 'Aanya Homecraft B2B Kitchenware & Cookware Supplier UAE | Triply Cookware, Cutlery, Storage — WCC Fashions',
    metaDescription: 'UAE wholesale supplier of premium kitchenware, tri-ply cookware, elegant cutlery, wood serveware, and kitchen organizers. Bulk supply for hospitality and retail.',
    keywords: ['Aanya Homecraft UAE', 'wholesale kitchenware Dubai', 'triply cookware bulk order', 'cutlery supplier UAE', 'wooden serveware wholesale', 'kitchen organizers bulk Dubai', 'B2B home essentials UAE', 'hotel kitchenware supplier Middle East'],
    heroHeading: 'Premium Cookware & Kitchen Essentials at Scale.',
    heroSubtitle: 'Triply stainless steel cookware, premium cutlery, artisan wood serveware, and smart organizers — manufactured in collaboration with Aanya Homecraft.',
    stat1Label: 'MOQ From', stat1Value: '100 Units',
    stat2Label: 'Lead Time', stat2Value: '10–20 Days',
    stat3Label: 'Brand Partner', stat3Value: 'Aanya Homecraft',
    categories: [
      { id: 'HH-CAT-01', name: 'Triply Cookware', slug: 'cookware', status: 'active' as const, displayOrder: 1, subCategories: [] },
      { id: 'HH-CAT-02', name: 'Premium Cutlery', slug: 'cutlery', status: 'active' as const, displayOrder: 2, subCategories: [] },
      { id: 'HH-CAT-03', name: 'Table & Serveware', slug: 'table-top', status: 'active' as const, displayOrder: 3, subCategories: [] },
      { id: 'HH-CAT-04', name: 'Storage & Organizer', slug: 'utility', status: 'active' as const, displayOrder: 4, subCategories: [] },
    ],
  },

  {
    name: 'Hospitality',
    slug: 'hospitality',
    icon: 'DIV-03',
    status: 'expanding' as const,
    description: 'Premium hospitality textiles, uniforms, and commercial kitchenware',
    metaTitle: 'Horeca24h Hotel Linen & B2B Commercial Kitchenware Supplier UAE — WCC Fashions',
    metaDescription: 'UAE wholesale supplier of premium hotel bed linen, chef uniforms, and Horeca24h commercial kitchenware, cookware, table cutlery, barware, and buffet serving equipment.',
    keywords: ['hotel linen supplier UAE', 'hospitality uniform manufacturer Dubai', 'Horeca24h UAE', 'commercial kitchenware bulk Dubai', 'hotel cutlery supplier UAE', 'restaurant cookware wholesale', 'barware wholesale UAE', 'hotel buffet serving tools'],
    heroHeading: 'Finest B2B Hospitality Textiles & Horeca Equipment.',
    heroSubtitle: 'From 5-star hotel linens to Horeca24h professional cookware, cutlery, barware, and buffet serving tools — outfitting global hospitality.',
    stat1Label: 'MOQ From', stat1Value: '50 Units',
    stat2Label: 'Lead Time', stat2Value: '12–20 Days',
    stat3Label: 'Brand Partner', stat3Value: 'Horeca24h',
    categories: [
      { id: 'HOS-CAT-07', name: 'Barware Products', slug: 'barware', status: 'active' as const, displayOrder: 1, subCategories: [] },
      { id: 'HOS-CAT-08', name: 'Cookware Products', slug: 'cookware', status: 'active' as const, displayOrder: 2, subCategories: [] },
      { id: 'HOS-CAT-09', name: 'Serving & Kitchen Tools', slug: 'serving-tools', status: 'active' as const, displayOrder: 3, subCategories: [] },
      { id: 'HOS-CAT-10', name: 'Table Cutlery', slug: 'cutlery', status: 'active' as const, displayOrder: 4, subCategories: [] },
      { id: 'HOS-CAT-11', name: 'Storage & Serving', slug: 'storage-serving', status: 'active' as const, displayOrder: 5, subCategories: [] },
    ],
  },

  {
    name: 'Uniforms',
    slug: 'uniforms',
    icon: 'DIV-04',
    status: 'established' as const,
    description: 'Professional uniform solutions for all sectors',
    metaTitle: 'Uniform Supplier Dubai | Bulk Workwear, Security & Corporate Uniforms — WCC Garments',
    metaDescription: 'UAE-based uniform manufacturer supplying workwear, security uniforms, corporate attire & industrial PPE in bulk. Serving hotels, hospitals, oil & gas. Request a quote.',
    keywords: ['uniform supplier Dubai', 'workwear manufacturer UAE', 'corporate uniform bulk order', 'security uniform supplier UAE', 'industrial workwear Dubai', 'hotel staff uniform manufacturer', 'safety uniform UAE', 'bulk uniform order Middle East', 'tactical uniform supplier', 'B2B uniform factory Dubai'],
    heroHeading: 'Professional Uniforms for Every Sector.',
    heroSubtitle: 'From industrial cargo wear to tactical security suites — bulk uniform solutions engineered for performance and compliance.',
    stat1Label: 'MOQ From', stat1Value: '100 Units',
    stat2Label: 'Lead Time', stat2Value: '15–30 Days',
    stat3Label: 'Sectors', stat3Value: '10+',
    categories: [
      { id: 'UNI-CAT-01', name: 'Corporate Workwear', slug: 'corporate-workwear', status: 'active' as const, displayOrder: 1, subCategories: [] },
      { id: 'UNI-CAT-02', name: 'Security Attire', slug: 'security-attire', status: 'active' as const, displayOrder: 2, subCategories: [] },
      { id: 'UNI-CAT-03', name: 'Industrial & PPE', slug: 'industrial-ppe', status: 'active' as const, displayOrder: 3, subCategories: [] },
      { id: 'UNI-CAT-04', name: 'Chef & Kitchen Wear', slug: 'chef-kitchen-wear', status: 'active' as const, displayOrder: 4, subCategories: [] },
      { id: 'UNI-CAT-05', name: 'Protective Aprons', slug: 'protective-aprons', status: 'active' as const, displayOrder: 5, subCategories: [] },
      { id: 'UNI-CAT-06', name: 'Medical & Scrubs', slug: 'medical-scrubs', status: 'coming-soon' as const, displayOrder: 6, subCategories: [] },
    ],
  },

  {
    name: 'Home',
    slug: 'home',
    icon: 'DIV-05',
    status: 'expanding' as const,
    description: 'Luxury home linen and furnishing textiles',
    metaTitle: 'Home Linen Wholesale UAE | Bedsheets, Bath Towels & Luxury Throws — WCC Garments',
    metaDescription: 'Bulk home textile manufacturer in Dubai. Premium bedsheets, bath towels, cashmere throws & home furnishing textiles. Wholesale pricing for retailers & distributors.',
    keywords: ['home linen wholesale UAE', 'bedsheet manufacturer Dubai', 'bath towel bulk order UAE', 'home textile supplier Middle East', 'luxury throws wholesale', 'cotton bedding manufacturer UAE', 'wholesale home furnishing textiles', 'cashmere blanket bulk supplier', 'ring spun towel manufacturer Dubai', 'B2B home linen distributor'],
    heroHeading: 'Luxury Home Textiles for Retailers & Distributors.',
    heroSubtitle: 'Premium bedsheets, plush bath towels, and cashmere throws — built for bulk retail and private-label distribution.',
    stat1Label: 'MOQ From', stat1Value: '100 Units',
    stat2Label: 'Lead Time', stat2Value: '10–30 Days',
    stat3Label: 'Thread Count', stat3Value: 'Up to 600TC',
    categories: [
      {
        id: 'HOME-CAT-01', name: 'Bedsheets', slug: 'bedsheets', status: 'active' as const, displayOrder: 1,
        subCategories: [
          { id: 'HOME-SUB-01', name: 'Fitted Sheets', slug: 'fitted-sheets', status: 'active' as const, displayOrder: 1 },
          { id: 'HOME-SUB-02', name: 'Flat Sheets', slug: 'flat-sheets', status: 'active' as const, displayOrder: 2 },
          { id: 'HOME-SUB-03', name: 'Pillow Covers', slug: 'pillow-covers', status: 'active' as const, displayOrder: 3 },
        ],
      },
      {
        id: 'HOME-CAT-02', name: 'Bath Textiles', slug: 'bath-textiles', status: 'active' as const, displayOrder: 2,
        subCategories: [
          { id: 'HOME-SUB-04', name: 'Bath Towels', slug: 'bath-towels', status: 'active' as const, displayOrder: 1 },
          { id: 'HOME-SUB-05', name: 'Hand Towels', slug: 'hand-towels', status: 'active' as const, displayOrder: 2 },
          { id: 'HOME-SUB-06', name: 'Bath Sheets', slug: 'bath-sheets', status: 'active' as const, displayOrder: 3 },
        ],
      },
      {
        id: 'HOME-CAT-03', name: 'Luxury Throws', slug: 'luxury-throws', status: 'active' as const, displayOrder: 3,
        subCategories: [
          { id: 'HOME-SUB-07', name: 'Cashmere Throws', slug: 'cashmere-throws', status: 'active' as const, displayOrder: 1 },
          { id: 'HOME-SUB-08', name: 'Merino Wool Blankets', slug: 'merino-blankets', status: 'active' as const, displayOrder: 2 },
        ],
      },
      {
        id: 'HOME-CAT-04', name: 'Table Linen', slug: 'table-linen', status: 'coming-soon' as const, displayOrder: 4,
        subCategories: [
          { id: 'HOME-SUB-09', name: 'Table Runners', slug: 'table-runners', status: 'coming-soon' as const, displayOrder: 1 },
          { id: 'HOME-SUB-10', name: 'Placemats', slug: 'placemats', status: 'coming-soon' as const, displayOrder: 2 },
        ],
      },
    ],
  },

  {
    name: 'Fragrance',
    slug: 'fragrance',
    icon: 'DIV-06',
    status: 'newly-started' as const,
    description: 'Perfumes, raw materials and private label',
    metaTitle: 'Wholesale Perfume & Fragrance Manufacturer UAE | Oud, Bakhoor, Private Label — WCC Garments',
    metaDescription: 'UAE-based fragrance manufacturer offering Arabian Oud, Bakhoor, Eau de Parfum & private label fragrance solutions in bulk. Ideal for retail, duty-free & gift shops.',
    keywords: ['wholesale perfume manufacturer UAE', 'oud fragrance supplier Dubai', 'private label perfume UAE', 'bakhoor supplier wholesale', 'Arabian fragrance manufacturer', 'Eau de Parfum bulk order', 'incense wholesale UAE', 'fragrance raw material supplier Dubai', 'luxury perfume B2B UAE', 'custom fragrance manufacturer Middle East'],
    heroHeading: 'Authentic Arabian Fragrances. Private Label Ready.',
    heroSubtitle: 'Oud, Bakhoor, Eau de Parfum — crafted in the UAE for retail chains, duty-free operators, and private label buyers worldwide.',
    stat1Label: 'MOQ From', stat1Value: '100 Units',
    stat2Label: 'Lead Time', stat2Value: '10–16 Days',
    stat3Label: 'Label Options', stat3Value: 'Private Label',
    categories: [
      { id: 'FRA-CAT-01', name: 'Arabian Oud', slug: 'arabian-oud', status: 'active' as const, displayOrder: 1, subCategories: [] },
      { id: 'FRA-CAT-02', name: 'Bakhoor & Incense', slug: 'bakhoor-incense', status: 'active' as const, displayOrder: 2, subCategories: [] },
      { id: 'FRA-CAT-03', name: 'Eau de Parfum', slug: 'eau-de-parfum', status: 'active' as const, displayOrder: 3, subCategories: [] },
      { id: 'FRA-CAT-04', name: 'Private Label', slug: 'private-label', status: 'active' as const, displayOrder: 4, subCategories: [] },
      { id: 'FRA-CAT-05', name: 'Raw Materials', slug: 'raw-materials', status: 'coming-soon' as const, displayOrder: 5, subCategories: [] },
    ],
  },
]
export const BUSINESS_TYPES = [
  'Wholesale Distributor',
  'Hotel / Hospitality',
  'Hospital / Healthcare',
  'Corporate / Uniforms',
  'Retail Chain',
  'Government / Tender',
  'Other',
]

export const PRODUCT_INTERESTS = [
  'Garments & Fashion',
  'Uniforms & Workwear',
  'Hospitality Textiles',
  'Home Furnishings',
  'Fragrance & Raw Materials',
  'Household Products',
  'Multiple Categories',
]

export const COUNTRIES = [
  'United Arab Emirates', 'Saudi Arabia', 'Kuwait', 'Bahrain', 'Qatar', 'Oman',
  'Nigeria', 'Kenya', 'South Africa', 'Ghana', 'Egypt', 'Ethiopia', 'Tanzania',
  'Uganda', 'Mozambique', 'Cameroon', 'Senegal', 'Ivory Coast',
  'India', 'Pakistan', 'Bangladesh', 'Sri Lanka',
  'United Kingdom', 'Germany', 'France', 'Italy', 'Spain',
  'United States', 'Canada', 'Brazil',
  'China', 'Japan', 'South Korea', 'Australia',
  'Turkey', 'Jordan', 'Iraq', 'Iran',
  'Other',
]

export const NAV_LINKS = [
  { name: 'Products', href: '/products' },
  { name: 'Garments', href: '/products/garments' },
  { name: 'New Arrivals', href: '/new-arrivals' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
]

export const ENQUIRY_STATUSES = [
  { value: 'new', label: 'New', color: '#3B82F6' },
  { value: 'contacted', label: 'Contacted', color: '#F59E0B' },
  { value: 'quoted', label: 'Quoted', color: '#8B5CF6' },
  { value: 'negotiating', label: 'Negotiating', color: '#EC4899' },
  { value: 'won', label: 'Won', color: '#10B981' },
  { value: 'lost', label: 'Lost', color: '#EF4444' },
]

export const MOCK_IMAGES = {
  hero: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1920&q=90',
  garments: '/images/garments-category.png',
  uniforms: '/images/uniform-workwear.png',
  hospitality: '/images/hospitality.png',
  home: '/images/home furnishing.png',
  fragrance: '/images/fragrance.png',
  households: '/images/household.png',
  factory: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=85',
  team: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=85',
  quality: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=85',
  fabric: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1200&q=90',
  sewing: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&q=90',
  textiles: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=1200&q=90',
}

export const MOCK_PRODUCTS: Array<{
  id: string
  name: string
  slug: string
  division: string
  division_slug: string
  category: string
  categories?: string[]
  short_description: string
  moq: string
  lead_time: string
  images: string[]
  is_new: boolean
  is_offer: boolean
  offer_label: string | null
  offer_start?: string
  offer_end?: string
  offer_terms?: string
  featured: boolean
  specifications: Record<string, string>
  custom_branding?: boolean
  certifications?: string[]
  suitable_for: string[]
  tags: string[]
  brand_slug?: string | null
}> = [
    {
      id: '1', name: 'Egyptian Cotton Premium Shirts', slug: 'egyptian-cotton-premium-shirts',
      division: 'Garments', division_slug: 'garments', category: 'Formal Shirts', categories: ['Formal Shirts'],
      short_description: 'Premium 100% Egyptian cotton shirts crafted for global wholesale distribution. Available in multiple fits and finishes.',
      moq: '500 units', lead_time: '15-25 working days',
      images: [
        '/images/products/egyptian_cotton_shirt.png',
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true, custom_branding: true, certifications: ['Export Grade QC'],
      specifications: { material: '100% Egyptian Cotton', thread_count: '300 TC', weight: '120 GSM', sizes: 'S, M, L, XL, XXL', colors: 'White, Sky Blue, Navy, Black' },
      suitable_for: ['Corporate', 'Retail', 'Hotels'],
      tags: ['cotton', 'formal', 'premium'],
      brand_slug: 'treasure',
    },
    {
      id: '2', name: 'Industrial Cargo Work Pants', slug: 'industrial-cargo-work-pants',
      division: 'Uniforms', division_slug: 'uniforms', category: 'Workwear', categories: ['Workwear'],
      short_description: 'Heavy-duty cargo work pants built for industrial environments. Reinforced stitching and multiple utility pockets.',
      moq: '300 units', lead_time: '20-30 working days',
      images: [
        '/images/products/cargo_work_pants.png',
        'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=85',
      ],
      is_new: false, is_offer: true, offer_label: 'Bulk Discount', offer_start: '2026-05-01', offer_end: '2026-06-30', offer_terms: 'Applicable for orders above 1,000 units. Subject to production slot confirmation.', featured: true, custom_branding: true, certifications: ['Industrial Workwear QA'],
      specifications: { material: 'Poly-Cotton Blend 65/35', weight: '280 GSM', sizes: '28-44 Waist', colors: 'Khaki, Navy, Black, Olive' },
      suitable_for: ['Construction', 'Manufacturing', 'Oil & Gas'],
      tags: ['workwear', 'industrial', 'cargo'],
    },
    {
      id: '3', name: 'Hotel Bed Linen Collection', slug: 'hotel-bed-linen-collection',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Bed Linen', categories: ['Bed Linen'],
      short_description: 'Luxury hotel-grade bed linen sets. Sateen weave finish with exceptional durability for commercial laundering.',
      moq: '200 sets', lead_time: '15-20 working days',
      images: [
        '/images/products/hotel_bed_linen.png',
        'https://images.unsplash.com/photo-1616627561839-074385245ff6?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true, custom_branding: true, certifications: ['Hospitality Textile QC'],
      specifications: { material: '100% Combed Cotton', thread_count: '300-600 TC', weave: 'Sateen', sizes: 'Single, Double, Queen, King' },
      suitable_for: ['Hotels', 'Resorts', 'Airlines'],
      tags: ['hotel', 'linen', 'luxury'],
    },
    {
      id: '4', name: 'Luxury Bath Towel Set', slug: 'luxury-bath-towel-set',
      division: 'Home', division_slug: 'home', category: 'Bath Textiles', categories: ['Bath Textiles'],
      short_description: 'Ultra-soft ring spun cotton towels with superior absorbency. Double-stitched hems for commercial durability.',
      moq: '1000 units', lead_time: '10-15 working days',
      images: [
        '/images/products/luxury_bath_towels.png',
        'https://images.unsplash.com/photo-1616627561839-074385245ff6?w=800&q=85',
      ],
      is_new: false, is_offer: true, offer_label: 'Seasonal Special', offer_start: '2026-05-10', offer_end: '2026-07-10', offer_terms: 'Offer applies to container-load and mixed-SKU bulk enquiries only.', featured: false, custom_branding: true,
      specifications: { material: '100% Ring Spun Cotton', weight: '500-700 GSM', sizes: 'Hand, Bath, Bath Sheet', colors: 'White, Ivory, Grey, Navy' },
      suitable_for: ['Hotels', 'Retail', 'Healthcare'],
      tags: ['towel', 'bath', 'cotton'],
    },
    {
      id: '5', name: 'Arabian Oud Collection', slug: 'arabian-oud-collection',
      division: 'Fragrance', division_slug: 'fragrance', category: 'Premium Fragrances', categories: ['Premium Fragrances'],
      short_description: 'Authentic Arabian Oud fragrances crafted from rare aged agarwood. Private label options available.',
      moq: '100 units', lead_time: '10-15 working days',
      images: [
        '/images/products/arabian_oud_perfume.png',
        'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true, custom_branding: true,
      specifications: { type: 'Eau de Parfum', concentration: '18-22%', sizes: '50ml, 100ml', notes: 'Oud, Rose, Amber, Musk' },
      suitable_for: ['Retail', 'Duty Free', 'Gift Shops'],
      tags: ['fragrance', 'oud', 'luxury'],
    },
    {
      id: '6', name: 'Premium Chef Uniform Set', slug: 'premium-chef-uniform-set',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Chef Uniforms', categories: ['Chef Uniforms'],
      short_description: 'Professional chef coats with breathable fabric and stain resistance. Double-breasted design with cloth buttons.',
      moq: '100 units', lead_time: '12-18 working days',
      images: [
        '/images/products/chef_uniform.png',
        'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true, custom_branding: true,
      specifications: { material: 'Poly-Cotton Twill', weight: '200 GSM', sizes: 'XS-3XL', colors: 'White, Black, Grey' },
      suitable_for: ['Restaurants', 'Hotels', 'Catering'],
      tags: ['chef', 'uniform', 'hospitality'],
    },
    {
      id: '7', name: 'Triply Stainless Steel Casserole', slug: 'triply-stainless-steel-casserole',
      division: 'Households', division_slug: 'households', category: 'Triply Cookware', categories: ['Triply Cookware'],
      short_description: 'Premium triply stainless steel cooking and serving casserole with induction compatible lid. Designed for even heating.',
      moq: '100 units', lead_time: '12-15 working days',
      images: [
        '/images/hh-1.png',
        'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Triply Stainless Steel', capacity: '3.5 Liters', handles: 'Stay-Cool Cast Steel', compatibility: 'Induction, Gas, Halogen' },
      suitable_for: ['Home Kitchens', 'Hotels', 'Catering'],
      tags: ['cookware', 'triply', 'casserole'],
    },
    {
      id: '8', name: 'Executive Polo Collection', slug: 'executive-polo-collection',
      division: 'Garments', division_slug: 'garments', category: 'Polo Shirts', categories: ['Polo Shirts'],
      short_description: 'Premium pique cotton polo shirts with corporate customization. Ribbed collar and cuffs for refined appearance.',
      moq: '250 units', lead_time: '12-18 working days',
      images: [
        'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&q=85',
        'https://images.unsplash.com/photo-1622445262465-248197307967?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: false, custom_branding: true,
      specifications: { material: '100% Pique Cotton', weight: '220 GSM', sizes: 'S-3XL', colors: 'White, Navy, Black, Burgundy, Forest Green' },
      suitable_for: ['Corporate', 'Hotels', 'Events'],
      tags: ['polo', 'corporate', 'cotton'],
      brand_slug: 'tom-jack',
    },
    {
      id: '9', name: 'Executive Velvet Blazer', slug: 'executive-velvet-blazer',
      division: 'Garments', division_slug: 'garments', category: 'Formal Outerwear', categories: ['Formal Outerwear'],
      short_description: 'Luxury tailored velvet blazers engineered for VIP hospitality and front-of-house attire. Stain resistant coating.',
      moq: '50 units', lead_time: '14-20 working days',
      images: [
        'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&q=85',
        'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=85',
      ],
      is_new: false, is_offer: true, offer_label: 'VIP Package', offer_start: '2026-05-15', offer_end: '2026-08-15', offer_terms: 'Bundle includes branded packaging and priority sampling for qualified buyers.', featured: true, custom_branding: true,
      specifications: { material: 'Italian Cotton Velvet', weight: '320 GSM', sizes: '36-48 Chest', colors: 'Midnight Blue, Royal Black, Emerald' },
      suitable_for: ['Boutique Hotels', 'Luxury Lounges', 'Private Clubs'],
      tags: ['blazer', 'velvet', 'vip'],
      brand_slug: 'treasure',
    },
    {
      id: '10', name: 'Tactical Security Uniform Suite', slug: 'tactical-security-uniform-suite',
      division: 'Uniforms', division_slug: 'uniforms', category: 'Security Attire', categories: ['Security Attire'],
      short_description: 'Industrial ripstop tactical uniforms engineered for VIP security and protocol forces. Water and abrasion resistant coating.',
      moq: '200 units', lead_time: '18-25 working days',
      images: [
        'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=85',
        'https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true, custom_branding: true, certifications: ['Compliance-Ready Fabrics'],
      specifications: { material: '65% Polyester / 35% Cotton Ripstop', weight: '260 GSM', sizes: 'S-4XL', colors: 'Navy, Black, Desert Tan' },
      suitable_for: ['Security Firms', 'Hotels', 'Aviation'],
      tags: ['tactical', 'uniform', 'security'],
    },
    {
      id: '11', name: 'Cashmere Merino Hospitality Blanket', slug: 'cashmere-merino-hospitality-blanket',
      division: 'Home', division_slug: 'home', category: 'Luxury Throws', categories: ['Luxury Throws'],
      short_description: 'Exquisite blended cashmere and merino wool throws designed for five-star presidential suites and VIP aviation lounges.',
      moq: '100 units', lead_time: '20-30 working days',
      images: [
        'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=800&q=85',
        'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true, custom_branding: true,
      specifications: { material: '30% Mongolian Cashmere / 70% Merino Wool', weight: '450 GSM', dimensions: '180x220cm', colors: 'Warm Taupe, Charcoal, Oatmeal' },
      suitable_for: ['Luxury Hotels', 'Private Jets', 'High-End Retail'],
      tags: ['cashmere', 'blanket', 'home'],
    },
    {
      id: '12', name: 'Royal Majalis Bakhoor Infusion', slug: 'royal-majalis-bakhoor-infusion',
      division: 'Fragrance', division_slug: 'fragrance', category: 'Incense & Home Fragrance', categories: ['Incense & Home Fragrance'],
      short_description: 'Traditional royal Bakhoor compressed tablets rich in natural sandalwood, ambergris, and Taif rose essential oils.',
      moq: '300 boxes', lead_time: '12-16 working days',
      images: [
        'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=800&q=85',
        'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true, custom_branding: true,
      specifications: { format: 'Compressed Incense Tablets', weight: '150g per box', origin: 'UAE Crafted', notes: 'Sandalwood, Amber, Taif Rose' },
      suitable_for: ['Palaces', 'Luxury Hotels', 'Boutique Spas'],
      tags: ['bakhoor', 'fragrance', 'majalis'],
    },
    {
      id: '13', name: 'Heavy-Duty Industrial Apron Set', slug: 'heavy-duty-industrial-apron-set',
      division: 'Uniforms', division_slug: 'uniforms', category: 'Protective Workwear', categories: ['Protective Workwear'],
      short_description: 'Waxed cotton canvas aprons with genuine leather harness straps and solid brass hardware. Built for artisan workshops.',
      moq: '150 units', lead_time: '15-20 working days',
      images: [
        'https://images.unsplash.com/photo-1602573991155-21f0143bb45c?w=800&q=85',
        'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: false, custom_branding: true,
      specifications: { material: '16oz Waxed Cotton Canvas', straps: 'Full Grain Leather', hardware: 'Solid Brass', sizes: 'Adjustable One Size' },
      suitable_for: ['Coffee Roasters', 'Woodworking', 'Bespoke Kitchens'],
      tags: ['apron', 'workwear', 'canvas'],
    },
    {
      id: '14', name: 'Artisanal Acacia Wooden Bowl', slug: 'artisanal-acacia-wooden-bowl',
      division: 'Households', division_slug: 'households', category: 'Table & Serveware', categories: ['Table & Serveware'],
      short_description: 'Handcrafted premium acacia wooden serving bowl. Perfect for salads, fruits, table presentation, and everyday serving.',
      moq: '100 units', lead_time: '10-14 working days',
      images: [
        '/images/hh-3.png',
        'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Acacia Wood', finish: 'Food Grade Mineral Oil', diameter: '12 Inches', care: 'Hand Wash Only' },
      suitable_for: ['Restaurants', 'Hotels', 'Bespoke Kitchens'],
      tags: ['wooden', 'bowl', 'serveware'],
      brand_slug: 'aanya-homecraft',
    },
    {
      id: '15', name: 'Premium Silk Tie Collection', slug: 'premium-silk-tie-collection',
      division: 'Garments', division_slug: 'garments', category: 'Corporate Accessories', categories: ['Corporate Accessories'],
      short_description: 'Handcrafted jacquard woven 100% mulberry silk neckties. Custom monogramming and corporate gift box packaging available.',
      moq: '300 units', lead_time: '20-25 working days',
      images: [
        'https://images.unsplash.com/photo-1589756823695-278bc923f962?w=800&q=85',
        'https://images.unsplash.com/photo-1617137953288-c89b33a75908?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: false, custom_branding: true,
      specifications: { material: '100% Mulberry Silk', width: '8cm Classic Width', finish: 'Jacquard Weave', lining: '100% Wool Interlining' },
      suitable_for: ['Corporate Gifts', 'Airlines', 'Executive Protocol'],
      tags: ['silk', 'tie', 'corporate'],
      brand_slug: 'tom-jack',
    },
    {
      id: '16', name: 'Premium Hammered Cutlery Set', slug: 'premium-hammered-cutlery-set',
      division: 'Households', division_slug: 'households', category: 'Premium Cutlery', categories: ['Premium Cutlery'],
      short_description: 'Elegant 24-piece hammered stainless steel cutlery set with stand. Crafted for premium home dining experiences.',
      moq: '250 units', lead_time: '15-20 working days',
      images: [
        '/images/hh-2.png',
        'https://images.unsplash.com/photo-1617137953288-c89b33a75908?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true,
      specifications: { material: '18/10 Stainless Steel', finish: 'Hammered Silver', pieces: '24 Pcs with Stand', brand: 'Aanya Homecraft' },
      suitable_for: ['Fine Dining', 'Luxury Hotels', 'Retail Chains'],
      tags: ['cutlery', 'hammered', 'dining'],
      brand_slug: 'aanya-homecraft',
    },
    {
      id: '17', name: 'Acacia Wooden Partition Box', slug: 'acacia-wooden-partition-box',
      division: 'Households', division_slug: 'households', category: 'Storage & Organizer', categories: ['Storage & Organizer'],
      short_description: 'Premium acacia wood multipurpose storage box with glass lid and compartment organizers for dry fruits or kitchen essentials.',
      moq: '200 units', lead_time: '12-18 working days',
      images: [
        '/images/hh-4.png',
        'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: false,
      specifications: { material: 'Acacia Wood & Tempered Glass', compartments: '4 Compartments', finish: 'Natural Polished', brand: 'Aanya Homecraft' },
      suitable_for: ['Home Decor', 'Kitchen Storage', 'Gifting'],
      tags: ['storage', 'organizer', 'wooden'],
      brand_slug: 'aanya-homecraft',
    },
    {
      id: '18', name: 'Metal Wine Rack with Wooden Base – 31.5cm', slug: 'metal-wine-rack-with-wooden-base-31-5cm',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Barware Products', categories: ['Barware Products'],
      short_description: 'Elegant metal wire wine rack featuring a solid polished wooden base. Designed to safely store and display wine bottles in commercial hospitality and home bars.',
      moq: '100 units', lead_time: '12-18 working days',
      images: [
        '/images/products/hospitality/Metal Wine Rack/1pic.jpg',
        '/images/products/hospitality/Metal Wine Rack/2pic.jpg',
        '/images/products/hospitality/Metal Wine Rack/3pic.jpg',
        '/images/products/hospitality/Metal Wine Rack/4thpic.jpg',
        '/images/products/hospitality/Metal Wine Rack/5thpic.jpg',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Iron Wire & Acacia Wood Base', size: '31.5cm Length', brand: 'Horeca24h', sku: 'MI-5036' },
      suitable_for: ['Hotel Bars', 'Lounges', 'Fine Dining', 'Restaurants'],
      tags: ['barware', 'wine-rack', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '25', name: 'Moscow Mule Mug 500 ml – 500 ml', slug: 'moscow-mule-mug-500ml-black',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Barware Products', categories: ['Barware Products'],
      short_description: 'Premium hammered glossy black Moscow Mule mug. Double-walled stainless steel construction keeps specialty cocktails chilled longer.',
      moq: '200 units', lead_time: '12-15 working days',
      images: [
        '/images/products/hospitality/Moscow Mule Mug/1pic.jpg',
        '/images/products/hospitality/Moscow Mule Mug/2pic.jpg',
        '/images/products/hospitality/Moscow Mule Mug/3pic.jpg',
        '/images/products/hospitality/Moscow Mule Mug/4pic.jpg',
        '/images/products/hospitality/Moscow Mule Mug/5thpic.jpg',
        '/images/products/hospitality/Moscow Mule Mug/6thpic.jpg',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Stainless Steel', finish: 'Hammered Black', capacity: '500 ml', brand: 'Horeca24h', sku: 'MI-5026' },
      suitable_for: ['Hotel Bars', 'Lounges', 'Fine Dining', 'Restaurants'],
      tags: ['barware', 'mule-mug', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '26', name: 'Moscow Mule Mug 500 ml | Stainless Steel Cocktail Mug with Handle – 500', slug: 'moscow-mule-mug-500ml-copper',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Barware Products', categories: ['Barware Products'],
      short_description: 'Classic hammered copper Moscow Mule mug featuring a solid brass handle. Perfectly designed for cocktails, keeping drinks ice-cold and fresh.',
      moq: '200 units', lead_time: '12-15 working days',
      images: [
        '/images/products/copper_moscow_mule_mi5035.png',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Stainless Steel', finish: 'Hammered Copper & Brass Handle', capacity: '500 ml', brand: 'Horeca24h', sku: 'MI-5035' },
      suitable_for: ['Hotel Bars', 'Lounges', 'Fine Dining', 'Restaurants'],
      tags: ['barware', 'mule-mug', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '27', name: 'Stainless Steel Cocktail Mug with Handle – 500 ml', slug: 'stainless-steel-cocktail-mug-with-handle-500ml',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Barware Products', categories: ['Barware Products'],
      short_description: 'Unique rustic weathered copper-patina finished cocktail mug with a gold-tone handle. Combines premium B2B aesthetics with durable food-grade stainless steel.',
      moq: '200 units', lead_time: '12-15 working days',
      images: [
        '/images/products/rustic_cocktail_mug_mi5029.png',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Stainless Steel', finish: 'Rustic Patina Copper', capacity: '500 ml', brand: 'Horeca24h', sku: 'MI-5029' },
      suitable_for: ['Hotel Bars', 'Lounges', 'Fine Dining', 'Restaurants'],
      tags: ['barware', 'cocktail-mug', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '19', name: 'Horeca24h Triply Stock Pot', slug: 'horeca24h-triply-stock-pot',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Cookware Products', categories: ['Cookware Products'],
      short_description: 'Heavy-duty tri-ply stainless steel stock pot designed for restaurant kitchens. Induction ready with superior heat distribution.',
      moq: '50 units', lead_time: '15-20 working days',
      images: [
        '/images/hos-2.png',
        'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: true,
      specifications: { material: 'Tri-Ply Stainless Steel', capacity: '12 Liters', bottom: 'Induction Compatible Encapsulated Base', brand: 'Horeca24h' },
      suitable_for: ['Commercial Kitchens', 'Hotels', 'Catering'],
      tags: ['cookware', 'stock-pot', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '20', name: 'Horeca24h Stainless Steel Buffet Tongs', slug: 'horeca24h-stainless-steel-buffet-tongs',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Serving & Kitchen Tools', categories: ['Serving & Kitchen Tools'],
      short_description: 'Professional grade mirror-polished stainless steel buffet and serving tongs. Elegant scissor design for luxury table serving.',
      moq: '200 units', lead_time: '10-15 working days',
      images: [
        '/images/hos-3.png',
        'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: false,
      specifications: { material: '18/10 Stainless Steel', length: '10 Inches', finish: 'Mirror Polished', brand: 'Horeca24h' },
      suitable_for: ['Hotel Buffet', 'Catering Events', 'Banquet Halls'],
      tags: ['serving', 'tongs', 'buffet', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '21', name: 'Horeca24h Modern Cutlery Set', slug: 'horeca24h-modern-cutlery-set',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Table Cutlery', categories: ['Table Cutlery'],
      short_description: 'Luxury hotel-grade cutlery set, ergonomically balanced and highly polished. Suitable for high-end dining presentation.',
      moq: '250 sets', lead_time: '12-18 working days',
      images: [
        '/images/hos-4.png',
        'https://images.unsplash.com/photo-1617137953288-c89b33a75908?w=800&q=85',
      ],
      is_new: true, is_offer: false, offer_label: null, featured: true,
      specifications: { material: '18/10 Stainless Steel', finish: 'High Mirror Polish', pieces: '24 Pcs (6 Settings)', brand: 'Horeca24h' },
      suitable_for: ['Fine Dining', 'Luxury Hotels', 'VVIP Banquets'],
      tags: ['cutlery', 'tableware', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '22', name: 'Horeca24h Black Wire Buffet Basket', slug: 'horeca24h-black-wire-buffet-basket',
      division: 'Hospitality', division_slug: 'hospitality', category: 'Storage & Serving', categories: ['Storage & Serving'],
      short_description: 'Contemporary matte black powder-coated wire basket with a natural oil-finished acacia wood base. Perfect for bread and table serving.',
      moq: '150 units', lead_time: '12-18 working days',
      images: [
        '/images/hos-5.png',
        'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=85',
      ],
      is_new: false, is_offer: false, offer_label: null, featured: false,
      specifications: { material: 'Iron Wire & Acacia Wood', finish: 'Matte Black Powder Coat / Food-Safe Wood Oil', sizes: '30x20x10 cm', brand: 'Horeca24h' },
      suitable_for: ['Hotel Buffet', 'Bakeries', 'Table Presentation'],
      tags: ['storage', 'serving', 'basket', 'horeca24h'],
      brand_slug: 'horeca24h',
    },
    {
      id: '23', name: '17 Piece Trio Robust 18/10 Tri-Ply Cookware Set', slug: 'household-17-piece-trio-robust-tri-ply-cookware-set',
      division: 'Households', division_slug: 'households', category: 'Triply Cookware', categories: ['Triply Cookware'],
      short_description: 'Complete 17-piece robust 18/10 stainless steel tri-ply cookware, mixing & serving set. Elegant design for premium modern home kitchens.',
      moq: '50 sets', lead_time: '15-20 working days',
      images: [
        '/images/products/Trio Robust 1810/MI-5072_1.jpg',
        '/images/products/Trio Robust 1810/MI-5072_2.jpg',
        '/images/products/Trio Robust 1810/MI-5072_3.jpg',
        '/images/products/Trio Robust 1810/MI-5072_4.jpg',
        '/images/products/Trio Robust 1810/MI-5072_5.jpg',
        '/images/products/Trio Robust 1810/MI-5072_6.jpg',
        '/images/products/Trio Robust 1810/MI-5072_7.jpg',
        '/images/products/Trio Robust 1810/MI-5072_10.jpg',
        '/images/products/Trio Robust 1810/MI-5072_11.jpg',
      ],
      is_new: true, is_offer: true, offer_label: '50% OFF', featured: true,
      specifications: { material: '18/10 Stainless Steel', pieces: '17 Pcs Set', brand: 'Aanya Homecraft', sku: 'MI-5072-H', features: 'Ergonomic handles, induction compatible' },
      suitable_for: ['Modern Homes', 'Gifting', 'Culinary Enthusiasts'],
      tags: ['cookware', 'tri-ply', 'stainless-steel', 'set'],
      brand_slug: 'aanya-homecraft',
    },
    {
      id: '24', name: '3 Piece Trio Robust 18/10 Tri-Ply Stainless Steel Cookware Set', slug: 'household-3-piece-trio-robust-tri-ply-cookware-set',
      division: 'Households', division_slug: 'households', category: 'Triply Cookware', categories: ['Triply Cookware'],
      short_description: 'Essential 3-piece robust 18/10 stainless steel tri-ply cookware set. Encapsulated core for rapid and even heat distribution.',
      moq: '50 sets', lead_time: '15-20 working days',
      images: [
        '/images/products/3 Piece Trio/MI-5068_1.jpg',
        '/images/products/3 Piece Trio/MI-5068_2.jpg',
        '/images/products/3 Piece Trio/MI-5068_3.jpg',
        '/images/products/3 Piece Trio/MI-5068_7.jpg',
        '/images/products/3 Piece Trio/MI-5068_8.jpg',
        '/images/products/3 Piece Trio/MI-5068_9.jpg',
        '/images/products/3 Piece Trio/MI-5068_10.jpg',
      ],
      is_new: false, is_offer: true, offer_label: '56% OFF', featured: true,
      specifications: { material: '18/10 Stainless Steel', pieces: '3 Pcs Set', brand: 'Aanya Homecraft', sku: 'MI-5068-H', features: 'Encapsulated core, mirror finish' },
      suitable_for: ['Home Kitchens', 'Everyday Cooking'],
      tags: ['cookware', 'tri-ply', 'stainless-steel', 'set'],
      brand_slug: 'aanya-homecraft',
    },
  ]

export const MOCK_BRANDS = [
  {
    id: 'b1',
    name: 'TREASURE',
    slug: 'treasure',
    division_slug: 'garments',
    tagline: 'Sleek Corporate Tailoring & Bespoke Formal Wear',
    description: 'A distinguished name in executive and protocol apparel. Known for premium-cut 100% Egyptian cotton shirts, velvet blazers, and luxury formal trousers representing the apex of B2B corporate wear.',
    logo_mobile: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
    logo_desktop: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=1200&q=80',
    featured: true,
    display_order: 1,
    created_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'b2',
    name: 'VANDEGRAFF',
    slug: 'vandegraff',
    division_slug: 'garments',
    tagline: 'Heavy-Duty Corporate Attire & Technical Workwear',
    description: 'Engineered for absolute performance, high-grade twill corporate trousers, heavy-duty cargo wear, and premium corporate uniforms constructed with reinforced stitching and stain-resistant treatment.',
    logo_mobile: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
    logo_desktop: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80',
    featured: true,
    display_order: 2,
    created_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'b3',
    name: 'TOM & JACK',
    slug: 'tom-jack',
    division_slug: 'garments',
    tagline: 'Contemporary Active Apparel & Refined Team Wear',
    description: 'Modern, high-comfort garments designed for luxury hospitality staff, VIP events, and professional team environments. Specialists in double-mercerized cotton polo shirts and elegant corporate accessories.',
    logo_mobile: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&q=80',
    logo_desktop: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=1200&q=80',
    featured: true,
    display_order: 3,
    created_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'b4',
    name: 'HORECA24H',
    slug: 'horeca24h',
    division_slug: 'hospitality',
    tagline: 'Premium Hospitality Serveware & Bar Accessories',
    description: 'Elegant serveware, copper mule mugs, cocktail tools, and table cutlery designed for F&B establishments, hotels, and luxury catering services.',
    logo_mobile: '/images/logo/horeca24h.png',
    logo_desktop: '/images/logo/horeca24h.png',
    featured: true,
    display_order: 4,
    created_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'b5',
    name: 'AANYA HOMECRAFT',
    slug: 'aanya-homecraft',
    division_slug: 'households',
    tagline: 'Artisanal Woodenware & High-Performance Cookware',
    description: 'Premium tri-ply stainless steel cookware and handcrafted acacia wood serving bowls. Fusing traditional craftsmanship with modern kitchen utility.',
    logo_mobile: '/images/logo/aanyahomecraft.png',
    logo_desktop: '/images/logo/aanyahomecraft.png',
    featured: true,
    display_order: 5,
    created_at: '2026-01-01T00:00:00Z'
  }
]

